admins: []
forwards:
- source: -1541297064
  dest:
  - envato_freepik_premium
  offset: 1
  end: null
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 4.0
plugins:
  filter:
    text:
      blacklist:
      - freepik_premium_lk
