admins: []
forwards:
- source: -1001260894987
  dest:
  - testb0tb
  offset: 12723
  end: 0
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 3.0
plugins:
  filter:
    text:
      blacklist:
      - badword
